# .github/workflows/docker-build.yml

name: 手动构建多架构Docker镜像

on:
  # 允许您在 Actions 标签页手动触发此工作流
  workflow_dispatch:
    inputs:
      repo_url:
        description: '要克隆的GitHub仓库链接 (例如: https://github.com/your-name/your-repo.git)'
        required: true
      repo_ref:
        description: '要检出的分支、标签或提交SHA (例如: main)'
        required: true
        default: 'main'
      image_name:
        description: '要设置的镜像名称 (例如: my-awesome-app)'
        required: true
        default: 'my-app'
      tags:
        # 新增：标签输入
        description: '要推送的标签, 逗号分隔 (例如: v1.0,latest)'
        required: true
        default: 'latest'
      platforms:
        description: '要构建的平台, 逗号分隔 (留空则默认全部)'
        required: false
        default: 'linux/amd64,linux/arm64,linux/arm/v7'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    # 新增：为 GITHUB_TOKEN 授予写包权限，这是修复错误的关键
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: 1. 克隆指定的代码仓库
        run: |
          git clone ${{ github.event.inputs.repo_url }} app
          cd app
          git checkout ${{ github.event.inputs.repo_ref }}
      
      - name: 2. 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 3. 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 4. 登录到 GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 5. 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 6. 提取 Docker 元数据并生成标签
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.image_name }}
          # 修改：使用输入的标签，而不是自动生成
          tags: |
            type=csv,value=${{ github.event.inputs.tags }}

      - name: 7. 构建并推送到多个镜像仓库
        uses: docker/build-push-action@v6
        with:
          context: ./app
          platforms: ${{ github.event.inputs.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
